export const BEER_ACTION_TYPES = {
  GET_BEERS_REQUEST: "GET_BEERS_REQUEST",
  GET_BEERS_SUCCESS: "GET_BEERS_SUCCESS",
  GET_BEERS_FAILURE: "GET_BEERS_FAILURE",

  SET_BEERS_FILTER: "SET_BEERS_FILTER",
  CANCEL_BEERS_FILTER: "CANCEL_BEERS_FILTER",
};

export const BEER_TABLE_COLUMN_HEADER_ACTION_TYPES = {
  SET_COLUMN_HEADER: "SET_COLUMN_HEADER",
};

export const CART_ACTION_TYPES = {
  ADD_CART_ITEM_REQUEST: "ADD_CART_ITEM_REQUEST",
  ADD_CART_ITEM_SUCCESS: "ADD_CART_ITEM_SUCCESS",
  ADD_CART_ITEM_FAILURE: "ADD_CART_ITEM_FAILURE",

  DELETE_CART_ITEM_REQUEST: "DELETE_CART_ITEM_REQUEST",
  DELETE_CART_ITEM_SUCCESS: "DELETE_CART_ITEM_SUCCESS",
  DELETE_CART_ITEM_FAILURE: "DELETE_CART_ITEM_FAILURE",
};
