export const BEER_ACTION_TYPES = {
  GET_BEERS_REQUEST: "GET_BEERS_REQUEST",
  GET_BEERS_SUCCESS: "GET_BEERS_SUCCESS",
  GET_BEERS_FAILURE: "GET_BEERS_FAILURE",
};

export const BEER_TABLE_COLUMN_HEADER_TYPES = {
  SET_COLUMN_HEADER: "SET_COLUMN_HEADER",
};
